name: prueba_mas_nick
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_database: ^10.3.4
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  flutter_native_splash: ^2.3.5
  flutter_rating_bar: ^4.0.1
  like_button: ^2.0.5
  get: 4.6.6
  google_sign_in: ^5.4.2
  shared_preferences: ^2.2.2
  social_login_buttons: ^1.0.7

flutter_native_splash:
  android: true

  background_image: "assets/images/masuno_logo.jpg"
  color: #FFFFFF
    null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
